### ISSUE TITLE
More icons?

### ISSUE THREAD

**Issue by eitsupi** [quarto-ext/fontawesome#1]
Hi, thank you for this great extension.

Do you have information on which icons are included?
For example, `rabbit` does not seem to be available.

**Comment by eitsupi** [comment]
It seems that we can only use icons which have `solid`?

https://github.com/quarto-ext/fontawesome/blob/a5baffa1f22f735469bf3b24a77e6f8d99007797/_extensions/fontawesome/fontawesome.lua#L26

**Comment by mcanouil** [comment]
Indeed, I tried to use brands icons, but because "fa-solid" is hardcoded it is not possible.

See https://github.com/RLille/rlille.fr/pull/12 and Netlify preview

<img width="1510" alt="image" src="https://user-images.githubusercontent.com/8896044/178025694-ba83ad36-42b0-4b60-bba7-a3a907dd2bd4.png">

**Comment by jjallaire** [comment]
Just added support for the `brands` prefix. Updated docs here:

https://github.com/quarto-ext/fontawesome

Note that only the _free_ fontawesome icons are supported, and `rabbit` does not appear to be a free icon. You could use it by purchasing a Pro plan and then overwriting the `assets` directory within the extension with the Pro icons.

**Comment by eitsupi** [comment]
Thank you for updating immediately.
Do you have any plans for release?

**Comment by mcanouil** [comment]
@eitsupi When you install the extension you get the HEAD of the repository.
I already reinstalled the extension and used it for https://rlille.fr
(To note, at first there was a weird behaviour, so I updated Quarto to the latest and it works smoothly).

**Comment by eitsupi** [comment]
> When you install the extension you get the HEAD of the repository.

Thanks pointing this out. It works! (Perhaps there is currently no way to specify tags?)

By the way, the font list seems to include regular but the following code did not work. Am I missing something?

`{{< fa regular arrow-up-right-from-square >}}`

https://fontawesome.com/icons/arrow-up-right-from-square?s=regular

**Comment by dragonstyle** [comment]
> Thanks pointing this out. It works! (Perhaps there is currently no way to specify tags?)

We are working on documentation for extensions now, but you can use tags as well, like:

`quarto install extension quarto-ext/fontawesome@<tagname>`

**Comment by eitsupi** [comment]
> We are working on documentation for extensions now, but you can use tags as well, like:
> 
> `quarto install extension quarto-ext/fontawesome@<tagname>`

Thank you for letting me know. Makes sense, as this is a common way of specifying!
(I tried it but forgot the `v` and it failed, so I mistakenly thought it couldn't be done......)

**Comment by dragonstyle** [comment]
It's great to have you using all of this, thank you!

**Comment by mcanouil** [comment]
> {{< fa regular arrow-up-right-from-square >}}

@eitsupi This one is not amongst the 2,009 free icons (See <https://fontawesome.com/search?m=free>).
`{{< fa regular share-from-square >}}` works for instance.

**Comment by eitsupi** [comment]
> This one is not amongst the 2,009 free icons (See [fontawesome.com/search?m=free](https://fontawesome.com/search?m=free)).
> `{{< fa regular share-from-square >}}` works for instance.

Thanks, I finally understand.......

![image](https://user-images.githubusercontent.com/50911393/178281510-718734c0-eee1-4abf-a487-67be2f9eca54.png)
![image](https://user-images.githubusercontent.com/50911393/178281594-ce1310f4-06eb-4f8d-8eef-f3438717bc04.png)

**Comment by mcanouil** [comment]
I doubled check and apparently light/thin aren't free^^
![image](https://user-images.githubusercontent.com/8896044/178282280-b734bceb-8cf4-41d2-9ad5-3d25e9a35a6c.png)

Only 162 out of the 2,009 free icons have "regular" form available
