### ISSUE TITLE
FA shortcode in indented text (pre/code block) not displaying icon

### ISSUE THREAD

**Issue by mcanouil** [quarto-ext/fontawesome#13]
### Discussed in https://github.com/quarto-dev/quarto-cli/discussions/1619

The following code does not display FA icon in code block. 

```
---
title: "Untitled"
format: html
---

    {{< meta title >}}

    {{< fa thumbs-up >}}

```

```
<pre><code>Untitled


</code></pre>
```

**Comment by cscheid** [comment]
I don't think we want to resolve the HTML icon inside a code block, but we should be issuing a warning or error message. Unfortunately, I think this needs to be solved in quarto itself, and not in the extension.

**Comment by mcanouil** [comment]
I was not 100 % if it was indeed in Quarto.
And agree, about issuing a warning rather than allowing shortcode to display html icon in a code block (this is really a cumbersome thing to do 😅).
I'll still investigate a bit while trying to finalise #12
