### ISSUE TITLE
No longer working with self contained: true 

### ISSUE THREAD

**Issue by garthtarr** [quarto-ext/fontawesome#15]
I'm using the latest dev version of quarto-cli. The fontawesome extension was working fine with `self-contained: true` but looks to have recently stopped working:

```
---
title: "Self contained true"
format: 
  html:
    self-contained: true
---

{{< fa thumbs-up >}}
{{< fa folder >}}
{{< fa chess-pawn >}}
{{< fa brands bluetooth >}}
{{< fa brands twitter size=2xl >}}
{{< fa brands github size=5x >}}
{{< fa battery-half size=Huge >}}
{{< fa envelope title="An envelope" >}}
```
<img width="493" alt="Screen Shot 2022-08-22 at 8 45 53 pm" src="https://user-images.githubusercontent.com/2189134/185903604-6f3564a3-7ec8-466e-a6ca-a52f26c3f5f2.png">

Self-contained `false` still works fine:

<img width="536" alt="Screen Shot 2022-08-22 at 8 45 39 pm" src="https://user-images.githubusercontent.com/2189134/185903654-8f8a49bd-e183-4019-abd9-ab685e4fb908.png">

**Comment by cderv** [comment]
This should be fixed in last prerelease. Please reopen if there is still something wrong
