### ISSUE TITLE
Issue while compiling html with quarto and fontawesome

### ISSUE THREAD

**Issue by gsaabogado** [quarto-ext/fontawesome#19]
When trying to run a Quarto html document with the extension, I get the error.

output file: cv.knit.md

Error running filter C:/Users/Sarmiento/AppData/Local/Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:
_extensions/quarto-ext/fontawesome/fontawesome.lua:56: attempt to call a nil value (field 'is_format')
stack traceback:
        .../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:2943: in function 'callShortcodeHandler'
        .../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:3024: in function 'transformShortcodeInlines'
        .../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:2833: in function <.../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:2827>
        [C]: in function 'string.gsub'
        .../Programs/Quarto/share/filters/quarto-pre/quarto-pre.lua:2827: in function 'transformShortcodeCode'

So you know how can I fix this error? or is it related to the extension itself?

**Comment by cscheid** [comment]
Can you share a single .qmd that triggers this issue for us?

**Comment by eitsupi** [comment]
Could this be because the current main requires quarto 1.2?
Specifying v0.0.1 and installing it may solve the problem.
6206fc623371158bb84225803211f5fcaf73067a

**Comment by cscheid** [comment]
I'm going to speculatively close this one because I suspect eitsupi is correct in their assessment. I changed the README.md to indicate the version requirement, but please reopen the issue if you find that this doesn't work for you.
