### ISSUE TITLE
The URL link disappers when switch tabs between souce and visual in Quarto

### ISSUE THREAD

**Issue by koliajaykr** [quarto-ext/fontawesome#21]
```
---
title: "text example"
author: "ajay"
format: revealjs
editor: visual
---
```

## My Website

Please use this [link](https://koliajay.netlify.app/)

## FA Icon

{{< fa globe >}} My website [link](https://koliajay.netlify.app/)

***********************

In the above example, when we switch tabs between the "Source" and "Visual" the URL link next to the used font icon disappears.

**Comment by cscheid** [comment]
This appears to be an issue with the RStudio IDE from your mention of "Source" and "Visual". If that's the case, please file the bug on the RStudio repository: https://github.com/rstudio/rstudio.

**Comment by koliajaykr** [comment]
Filed bug issue on the RStudio repository.
