### ISSUE TITLE
Any plans to support the new Twitter/X Logo?

### ISSUE THREAD

**Issue by NMarkgraf** [quarto-ext/fontawesome#28]
Hi folks!

As far as I can see the current fontawesome(-extention) can't display the new X Logo (formerly know as twitter). Does someone have a work around or will there be an update soon?

Yours
Norman

**Comment by cderv** [comment]
This is a matter of updating fontawesome to use 6.4.2 version : https://fontawesome.com/icons/x-twitter?f=brands&s=solid

* https://github.com/FortAwesome/Font-Awesome/issues/19827#issuecomment-1662978580
