### ISSUE TITLE
Icon doesn't show up in blog post preview

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [quarto-ext/fontawesome#7]
I have a font awesome icon in the first sentence of [this post](https://mine-cetinkaya-rundel.github.io/quarto-tip-a-day/posts/18-font-awesome/). But it doesn't show up in the post preview.

<img width="286" alt="Screen Shot 2022-07-16 at 7 37 41 AM" src="https://user-images.githubusercontent.com/5965649/179366059-92035f58-9f02-4852-8936-0f59c6a62d85.png">

**Comment by mcanouil** [comment]
When a FA shortcode is explicitly called on the main/index page, the FA icon appears.
(I noticed this when trying to check #6: https://github.com/quarto-ext/fontawesome/issues/6#issuecomment-1186449728)

| Without explicit shortcode in `_quarto.yml` | With explicit shortcode in `_quarto.yml` |
|:----:|:---:|
| <img width="1624" alt="image" src="https://user-images.githubusercontent.com/8896044/179391336-df12aad0-e8e4-4af6-b2fd-cf19999995e9.png"> | <img width="1624" alt="Screenshot 2022-07-17 at 10 49 45" src="https://user-images.githubusercontent.com/8896044/179391111-f2c0be60-58e0-4722-bcbf-73c89472860f.png"> |

Meaning, FA is not fully accessible to the whole website when Quarto is rendering it for some reason.

**Comment by cscheid** [comment]
(Sorry for the delay) Is the issue here that the shortcode gets "transplanted" to the main page through a listing? If so, that's actually an interesting bug that we need to think about.

**Comment by mine-cetinkaya-rundel** [comment]
Yup, the icon/shortcode is in the blog post (listing), but the icon is not visible in the homepage that shows the blog post/listing preview.

**Comment by cscheid** [comment]
@mine-cetinkaya-rundel I'm tracking this as a bug on the quarto-cli repository now, so I'm going to close it here. Thanks for the report, this is a substantial bug!
